--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCEPTANCE_TRUCK
--------------------------------------------------------

  CREATE TABLE "PROJECT"."ACCEPTANCE_TRUCK" 
   (	"ACCEPTANCE_ID" NUMBER(8,0), 
	"TRUCK_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020107
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020107" ON "PROJECT"."ACCEPTANCE_TRUCK" ("ACCEPTANCE_ID", "TRUCK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACCEPTANCE_TRUCK
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ACCEPTANCE_TRUCK" ADD PRIMARY KEY ("ACCEPTANCE_ID", "TRUCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCEPTANCE_TRUCK
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ACCEPTANCE_TRUCK" ADD FOREIGN KEY ("ACCEPTANCE_ID")
	  REFERENCES "PROJECT"."ACCEPTANCE" ("ACCEPTANCE_ID") ENABLE;
  ALTER TABLE "PROJECT"."ACCEPTANCE_TRUCK" ADD FOREIGN KEY ("TRUCK_ID")
	  REFERENCES "PROJECT"."TRUCKS" ("TRUCK_ID") ENABLE;
