--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAREER
--------------------------------------------------------

  CREATE TABLE "PROJECT"."CAREER" 
   (	"CAREER_ID" NUMBER(8,0) DEFAULT "PROJECT"."CAREER_SEQ"."NEXTVAL", 
	"PERSONAL_ID" NUMBER(8,0), 
	"JOB_DIRECTORY_ID" NUMBER(8,0), 
	"PROMOTION_DATE" DATE DEFAULT NULL, 
	"PAST_JOB_DIRECTORY_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021194
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0021194" ON "PROJECT"."CAREER" ("CAREER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CAREER
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CAREER" ADD PRIMARY KEY ("CAREER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAREER
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CAREER" ADD FOREIGN KEY ("PERSONAL_ID")
	  REFERENCES "PROJECT"."EMPLOYEES" ("PERSONAL_ID") ENABLE;
  ALTER TABLE "PROJECT"."CAREER" ADD FOREIGN KEY ("JOB_DIRECTORY_ID")
	  REFERENCES "PROJECT"."JOB_DIRECTORY" ("JOB_DIRECTORY_ID") ENABLE;
  ALTER TABLE "PROJECT"."CAREER" ADD FOREIGN KEY ("PAST_JOB_DIRECTORY_ID")
	  REFERENCES "PROJECT"."JOB_DIRECTORY" ("JOB_DIRECTORY_ID") ENABLE;
