--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHECK_POSITION
--------------------------------------------------------

  CREATE TABLE "PROJECT"."CHECK_POSITION" 
   (	"CHECK_ID" NUMBER(10,0), 
	"PRICE_LIST_ID" NUMBER(8,0), 
	"AMOUNT" NUMBER(6,0), 
	"LOCAL_SUM" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHECK_POSITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."CHECK_POSITION_PK" ON "PROJECT"."CHECK_POSITION" ("CHECK_ID", "PRICE_LIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CHECK_POSITION
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CHECK_POSITION" MODIFY ("CHECK_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CHECK_POSITION" MODIFY ("PRICE_LIST_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CHECK_POSITION" ADD CONSTRAINT "CHECK_POSITION_PK" PRIMARY KEY ("CHECK_ID", "PRICE_LIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHECK_POSITION
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CHECK_POSITION" ADD FOREIGN KEY ("CHECK_ID")
	  REFERENCES "PROJECT"."CHECKS" ("CHECK_ID") ENABLE;
  ALTER TABLE "PROJECT"."CHECK_POSITION" ADD FOREIGN KEY ("PRICE_LIST_ID")
	  REFERENCES "PROJECT"."PRICE_LISTS" ("PRICE_LIST_ID") ENABLE;
