--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EXPENSE_OPERATION
--------------------------------------------------------

  CREATE TABLE "PROJECT"."EXPENSE_OPERATION" 
   (	"EXPENSE_ID" NUMBER(8,0), 
	"DEPT_ID" NUMBER(4,0), 
	"AMOUNT" NUMBER(5,0), 
	"INCOMING_ID" NUMBER(8,0), 
	"DATETIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020123
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020123" ON "PROJECT"."EXPENSE_OPERATION" ("EXPENSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger DEL_RESIDUE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROJECT"."DEL_RESIDUE" 
BEFORE DELETE ON EXPENSE_OPERATION 
FOR EACH ROW
BEGIN
  DELETE FROM residue re
    WHERE re.expense_id = :old.expense_id;
END;
/
ALTER TRIGGER "PROJECT"."DEL_RESIDUE" ENABLE;
--------------------------------------------------------
--  Constraints for Table EXPENSE_OPERATION
--------------------------------------------------------

  ALTER TABLE "PROJECT"."EXPENSE_OPERATION" ADD PRIMARY KEY ("EXPENSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."EXPENSE_OPERATION" MODIFY ("INCOMING_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EXPENSE_OPERATION
--------------------------------------------------------

  ALTER TABLE "PROJECT"."EXPENSE_OPERATION" ADD FOREIGN KEY ("DEPT_ID")
	  REFERENCES "PROJECT"."TRADING_FLOOR" ("DEPT_ID") ENABLE;
  ALTER TABLE "PROJECT"."EXPENSE_OPERATION" ADD CONSTRAINT "EXPENSE_OPERATION_FK1" FOREIGN KEY ("INCOMING_ID")
	  REFERENCES "PROJECT"."INCOMING_OPERATION" ("INCOMING_ID") ENABLE;
