--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOODS_OUTLET
--------------------------------------------------------

  CREATE TABLE "PROJECT"."GOODS_OUTLET" 
   (	"GOODS_ID" NUMBER(8,0) DEFAULT "PROJECT"."GOODS_OUTLET_SEQ"."NEXTVAL", 
	"GOODS_CARD_ID" NUMBER(8,0), 
	"AMOUNT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020161
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020161" ON "PROJECT"."GOODS_OUTLET" ("GOODS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GOODS_OUTLET
--------------------------------------------------------

  ALTER TABLE "PROJECT"."GOODS_OUTLET" ADD PRIMARY KEY ("GOODS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOODS_OUTLET
--------------------------------------------------------

  ALTER TABLE "PROJECT"."GOODS_OUTLET" ADD FOREIGN KEY ("GOODS_CARD_ID")
	  REFERENCES "PROJECT"."GOODS_CARD_COMPANY" ("GOODS_CARD_ID") ENABLE;
