--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOODS_CARD_COMPANY
--------------------------------------------------------

  CREATE TABLE "PROJECT"."GOODS_CARD_COMPANY" 
   (	"GOODS_CARD_ID" NUMBER(8,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"COMPANY_MANUFACTURER" VARCHAR2(100 BYTE), 
	"COUNTRY_MANUFACTURER" VARCHAR2(100 BYTE), 
	"CODE_MANUFACTURER" VARCHAR2(100 BYTE), 
	"SIZE_VAL" VARCHAR2(10 BYTE), 
	"UNITS" VARCHAR2(5 BYTE), 
	"BARCODE" VARCHAR2(100 BYTE), 
	"TECHNICAL_EXPIRATION_DATE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020084
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020084" ON "PROJECT"."GOODS_CARD_COMPANY" ("GOODS_CARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GOODS_CARD_COMPANY
--------------------------------------------------------

  ALTER TABLE "PROJECT"."GOODS_CARD_COMPANY" ADD PRIMARY KEY ("GOODS_CARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."GOODS_CARD_COMPANY" MODIFY ("COMPANY_MANUFACTURER" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."GOODS_CARD_COMPANY" MODIFY ("CODE_MANUFACTURER" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."GOODS_CARD_COMPANY" MODIFY ("BARCODE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."GOODS_CARD_COMPANY" ADD CONSTRAINT "GOODS_CARD_ID_NN" CHECK (Goods_card_id is not NULL
) ENABLE;
  ALTER TABLE "PROJECT"."GOODS_CARD_COMPANY" ADD CONSTRAINT "CODE_MANUF_NN" CHECK (code_manufacturer is not NULL) ENABLE;
  ALTER TABLE "PROJECT"."GOODS_CARD_COMPANY" ADD CONSTRAINT "COMPANY_MANUF_NN" CHECK (company_manufacturer is not NULL) ENABLE;
  ALTER TABLE "PROJECT"."GOODS_CARD_COMPANY" ADD CONSTRAINT "BARCODE_NN" CHECK (barcode is not NULL) ENABLE;
