--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOOD_GROUP
--------------------------------------------------------

  CREATE TABLE "PROJECT"."GOOD_GROUP" 
   (	"GOODS_CARD_ID" NUMBER(10,0), 
	"GROUP_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020094
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020094" ON "PROJECT"."GOOD_GROUP" ("GOODS_CARD_ID", "GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GOOD_GROUP
--------------------------------------------------------

  ALTER TABLE "PROJECT"."GOOD_GROUP" ADD PRIMARY KEY ("GOODS_CARD_ID", "GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."GOOD_GROUP" ADD CONSTRAINT "GO_CA_ID_NN" CHECK (Goods_card_id is not NULL) ENABLE;
  ALTER TABLE "PROJECT"."GOOD_GROUP" ADD CONSTRAINT "GR_ID_NN" CHECK (group_id is not NULL) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOOD_GROUP
--------------------------------------------------------

  ALTER TABLE "PROJECT"."GOOD_GROUP" ADD FOREIGN KEY ("GOODS_CARD_ID")
	  REFERENCES "PROJECT"."GOODS_CARD_COMPANY" ("GOODS_CARD_ID") ENABLE;
  ALTER TABLE "PROJECT"."GOOD_GROUP" ADD FOREIGN KEY ("GROUP_ID")
	  REFERENCES "PROJECT"."GROUPS_OF_GOODS" ("GROUP_ID") ENABLE;
