--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INCOMING_OPERATION
--------------------------------------------------------

  CREATE TABLE "PROJECT"."INCOMING_OPERATION" 
   (	"INCOMING_ID" NUMBER(8,0) DEFAULT "PROJECT"."INCOMING_OPERATION_SEQ"."NEXTVAL", 
	"GOODS_ID" NUMBER(8,0), 
	"BATCH_ID" NUMBER(15,0), 
	"MODULE_ID" NUMBER(4,0), 
	"EXPIRATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020118
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020118" ON "PROJECT"."INCOMING_OPERATION" ("INCOMING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger DEL_EXPENSE_OPERATION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROJECT"."DEL_EXPENSE_OPERATION" 
BEFORE DELETE ON INCOMING_OPERATION 
FOR EACH ROW
BEGIN
  DELETE FROM expense_operation eo
    WHERE eo.incoming_id = :old.incoming_id;
END;
/
ALTER TRIGGER "PROJECT"."DEL_EXPENSE_OPERATION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEL_WRITE_DOWN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROJECT"."DEL_WRITE_DOWN" 
BEFORE DELETE ON INCOMING_OPERATION 
FOR EACH ROW
BEGIN
  DELETE FROM write_downs wd
    WHERE wd.incoming_id = :old.incoming_id;
END;
/
ALTER TRIGGER "PROJECT"."DEL_WRITE_DOWN" ENABLE;
--------------------------------------------------------
--  Constraints for Table INCOMING_OPERATION
--------------------------------------------------------

  ALTER TABLE "PROJECT"."INCOMING_OPERATION" ADD PRIMARY KEY ("INCOMING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INCOMING_OPERATION
--------------------------------------------------------

  ALTER TABLE "PROJECT"."INCOMING_OPERATION" ADD CONSTRAINT "INCOMING_OPERATION_FK1" FOREIGN KEY ("GOODS_ID")
	  REFERENCES "PROJECT"."GOODS_OUTLET" ("GOODS_ID") ENABLE;
  ALTER TABLE "PROJECT"."INCOMING_OPERATION" ADD FOREIGN KEY ("BATCH_ID")
	  REFERENCES "PROJECT"."BATCHES" ("BATCH_ID") ENABLE;
  ALTER TABLE "PROJECT"."INCOMING_OPERATION" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "PROJECT"."WAREHOUSE" ("MODULE_ID") ENABLE;
