--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LEVEL_POSSIBILITY
--------------------------------------------------------

  CREATE TABLE "PROJECT"."LEVEL_POSSIBILITY" 
   (	"LEVEL_ID" NUMBER(8,0), 
	"POS_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021150
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0021150" ON "PROJECT"."LEVEL_POSSIBILITY" ("LEVEL_ID", "POS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LEVEL_POSSIBILITY
--------------------------------------------------------

  ALTER TABLE "PROJECT"."LEVEL_POSSIBILITY" ADD PRIMARY KEY ("LEVEL_ID", "POS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEVEL_POSSIBILITY
--------------------------------------------------------

  ALTER TABLE "PROJECT"."LEVEL_POSSIBILITY" ADD FOREIGN KEY ("POS_ID")
	  REFERENCES "PROJECT"."POSSIBILITIES" ("POS_ID") ENABLE;
