--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOG_IN
--------------------------------------------------------

  CREATE TABLE "PROJECT"."LOG_IN" 
   (	"PERSONAL_ID" NUMBER(8,0), 
	"PAY_DESK_ID" NUMBER(8,0), 
	"ENTRY_TIME" TIMESTAMP (6), 
	"EXIT_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020989
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020989" ON "PROJECT"."LOG_IN" ("PERSONAL_ID", "PAY_DESK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LOG_IN
--------------------------------------------------------

  ALTER TABLE "PROJECT"."LOG_IN" MODIFY ("ENTRY_TIME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."LOG_IN" MODIFY ("EXIT_TIME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."LOG_IN" ADD PRIMARY KEY ("PERSONAL_ID", "PAY_DESK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOG_IN
--------------------------------------------------------

  ALTER TABLE "PROJECT"."LOG_IN" ADD FOREIGN KEY ("PERSONAL_ID")
	  REFERENCES "PROJECT"."EMPLOYEES" ("PERSONAL_ID") ENABLE;
  ALTER TABLE "PROJECT"."LOG_IN" ADD FOREIGN KEY ("PAY_DESK_ID")
	  REFERENCES "PROJECT"."PAY_DESK" ("PAY_DESK_ID") ENABLE;
