--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDER_PRICES
--------------------------------------------------------

  CREATE TABLE "PROJECT"."ORDER_PRICES" 
   (	"ORDER_ID" NUMBER(8,0), 
	"PRICE_LIST_ID" NUMBER(7,0), 
	"GOODS_ID" NUMBER(6,0), 
	"TYPE_PRICE" NUMBER(5,0), 
	"TOTAL_PRICE" NUMBER(7,0), 
	"DATE_ORDER" DATE DEFAULT (sysdate), 
	"REGULAR_PRICE" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0021638
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0021638" ON "PROJECT"."ORDER_PRICES" ("ORDER_ID", "PRICE_LIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDER_PRICES
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ORDER_PRICES" ADD PRIMARY KEY ("ORDER_ID", "PRICE_LIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_PRICES
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ORDER_PRICES" ADD FOREIGN KEY ("PRICE_LIST_ID")
	  REFERENCES "PROJECT"."PRICE_LISTS" ("PRICE_LIST_ID") ENABLE;
