--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRICE_LISTS_HC
--------------------------------------------------------

  CREATE TABLE "PROJECT"."PRICE_LISTS_HC" 
   (	"PRICE_LIST_HC_ID" NUMBER(8,0), 
	"TYPE_PRICE" NUMBER(5,0), 
	"OUTLET_ID" NUMBER(6,0), 
	"GOODS_ID" NUMBER(8,0), 
	"ENTRY_PRICE" NUMBER(8,0), 
	"TOTAL_PRICE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020140
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020140" ON "PROJECT"."PRICE_LISTS_HC" ("PRICE_LIST_HC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRICE_LISTS_HC
--------------------------------------------------------

  ALTER TABLE "PROJECT"."PRICE_LISTS_HC" ADD PRIMARY KEY ("PRICE_LIST_HC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRICE_LISTS_HC
--------------------------------------------------------

  ALTER TABLE "PROJECT"."PRICE_LISTS_HC" ADD FOREIGN KEY ("TYPE_PRICE")
	  REFERENCES "PROJECT"."COUPONS" ("COUPON_ID") ENABLE;
