--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPORT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."REPORT" 
   (	"REPORT_ID" NUMBER(8,0) DEFAULT "PROJECT"."REPORT_SEQ"."NEXTVAL", 
	"PERSONAL_ID" NUMBER(8,0), 
	"FULL_NAME" VARCHAR2(255 BYTE), 
	"POST" VARCHAR2(60 BYTE), 
	"DEPARTMENT_ID" NUMBER(3,0), 
	"HOURS_WORKED" NUMBER(2,0), 
	"DAYS_WORKED" NUMBER(2,0), 
	"OVERWORKED_HOURS" NUMBER(2,0), 
	"OVERWORKED_DAYS" NUMBER(2,0), 
	"UNDERWORKED_HOURS" NUMBER(2,0), 
	"UNDERWORKED_DAYS" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020998
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020998" ON "PROJECT"."REPORT" ("REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."REPORT" ADD PRIMARY KEY ("REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."REPORT" ADD FOREIGN KEY ("PERSONAL_ID")
	  REFERENCES "PROJECT"."EMPLOYEES" ("PERSONAL_ID") ENABLE;
