--------------------------------------------------------
--  File created - суббота-апреля-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESIDUE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."RESIDUE" 
   (	"RESIDUE_ID" NUMBER(15,0), 
	"EXPENSE_ID" NUMBER(8,0), 
	"AMOUNT" NUMBER(5,0), 
	"GOODS_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020132
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SYS_C0020132" ON "PROJECT"."RESIDUE" ("RESIDUE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RESIDUE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."RESIDUE" ADD PRIMARY KEY ("RESIDUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESIDUE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."RESIDUE" ADD CONSTRAINT "RESIDUE_FK1" FOREIGN KEY ("GOODS_ID")
	  REFERENCES "PROJECT"."GOODS_OUTLET" ("GOODS_ID") ENABLE;
  ALTER TABLE "PROJECT"."RESIDUE" ADD FOREIGN KEY ("EXPENSE_ID")
	  REFERENCES "PROJECT"."EXPENSE_OPERATION" ("EXPENSE_ID") ENABLE;
